# Generated by Django 2.2.5 on 2019-09-22 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tienda', '0002_dias_tiendaworkingwindow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=150, null=True)),
                ('precio', models.DecimalField(decimal_places=3, default=0.0, max_digits=8)),
                ('tiempo_de_elaboracion', models.PositiveIntegerField(blank=True, default=0)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tienda.Tienda', verbose_name='Tiendas')),
            ],
        ),
    ]
