# Generated by Django 2.2.5 on 2019-09-23 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tienda', '0002_dias_tiendaworkingwindow'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_entrega_usuario', models.DateField()),
                ('precio_total_orden', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tienda.Tienda')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(blank=True, default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('precio_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orden.Orden')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.Producto')),
            ],
        ),
    ]
